use num_complex::{Complex, ComplexFloat};
use std::f32::consts::TAU;

// Derive normalized biquad coefficients from poles and zeros
pub fn get_biquad_coefficients(
  freq: f32,
  sample_rate: f32,
  bandwidth: f32,
) -> (Vec<Complex<f32>>, Vec<Complex<f32>>) {
  let (zeros, poles) = get_poles_and_zeros(freq, sample_rate, bandwidth);
  let mut b = poly_from_roots(&zeros);
  let a = poly_from_roots(&poles);
  let gain_correction = get_gain_correction(freq, sample_rate, &b, &a);
  b.iter_mut().for_each(|coeff| *coeff /= gain_correction);

  (b, a)
}

// Get poles and zeros for the bandpass filter
fn get_poles_and_zeros(
  freq: f32,
  sample_rate: f32,
  bandwidth: f32,
) -> ([Complex<f32>; 2], [Complex<f32>; 2]) {
  let theta = TAU * freq / sample_rate;
  let r = (-TAU * bandwidth / sample_rate).exp();

  let zeros = [Complex::new(1., 0.), Complex::new(-1., 0.)];
  let mut complex_poles = Complex::from_polar(r, theta);
  // Keep poles within the unit circle
  if complex_poles.abs() >= 0.999 {
    complex_poles *= 0.999 / complex_poles.abs();
  }

  (zeros, [complex_poles, complex_poles])
}

/// Get the gain correction factor to enforce 0 decibels gain for the filter
fn get_gain_correction(freq: f32, sample_rate: f32, b: &[Complex<f32>], a: &[Complex<f32>]) -> f32 {
  let omega = TAU * freq / sample_rate;
  let ejw = Complex::from_polar(1.0, -omega);
  let ejw2 = ejw * ejw;
  let numerator = b[0] + b[1] * ejw + b[2] * ejw2;
  let denominator = a[0] + a[1] * ejw + a[2] * ejw2;
  return (numerator / denominator).norm();
}

/// Compute polynomial coefficients from a sequence of roots
fn poly_from_roots(roots: &[Complex<f32>]) -> Vec<Complex<f32>> {
  if roots.is_empty() {
    panic!("Cannot compute the polynomial coefficients from an empty sequence.");
  }

  // Start with polynomial "1"
  let mut coeffs = vec![Complex::new(1.0, 0.0)];

  // Multiply (convolve) by (x - root) for each root
  for &root in roots {
    let mut new_coeffs = vec![Complex::new(0.0, 0.0); coeffs.len() + 1];
    for (i, &c) in coeffs.iter().enumerate() {
      new_coeffs[i] += c; // x^k term
      new_coeffs[i + 1] -= c * root; // x^(k-1) term
    }
    coeffs = new_coeffs;
  }

  coeffs
}

#[cfg(test)]
mod tests {
  use crate::{
    assert_approximately_eq,
    filter_bank::biquad_filters::utils::{get_biquad_coefficients, poly_from_roots},
  };
  use num_complex::Complex;

  /// Compare the polynomials generated by this Rust implementation with those generated by Python/scipy
  #[test]
  fn should_derive_polynomials_from_roots() {
    let result = poly_from_roots(&[
      Complex::new(0.78855293, 0.60504769),
      Complex::new(0.78855293, 0.60504769),
    ]);
    assert_approximately_eq!(result[0].re, 1., 7);
    assert_approximately_eq!(result[0].im, 0., 7);
    assert_approximately_eq!(result[1].re, -1.57710587, 7);
    assert_approximately_eq!(result[1].im, -1.21009539, 7);
    assert_approximately_eq!(result[2].re, 0.25573302, 7);
    assert_approximately_eq!(result[2].im, 0.95422427, 7);
  }

  /// Compare the coefficients generated by this Rust implementation with those generated by Python/scipy
  #[test]
  fn should_get_correct_biquad_coefficients() {
    let freq = 5000.;
    let sample_rate = 48000.;
    let q = 100.;
    let (b, a) = get_biquad_coefficients(freq, sample_rate, freq / q);
    assert_approximately_eq!(b[0].re, 3.49541903e-5, 5);
    assert_approximately_eq!(b[0].im, 0., 5);
    assert_approximately_eq!(b[1].re, 0., 5);
    assert_approximately_eq!(b[1].im, 0., 5);
    assert_approximately_eq!(b[2].re, -3.49541903e-5, 5);
    assert_approximately_eq!(b[2].im, 0., 5);
    assert_approximately_eq!(a[1].re, -1.57635562, 5);
    assert_approximately_eq!(a[1].im, -1.20958021, 5);
    assert_approximately_eq!(a[2].re, 0.25545319, 5);
    assert_approximately_eq!(a[2].im, 0.95336428, 5);
  }
}
